### ISSUE TITLE
A few remarks regarding the potential improvements discussed in README

### ISSUE THREAD

**Issue by simonbasle** [johncfranco/reactive-logger#9]
Hi,
I wanted to bring up some points regarding the potential improvements and architecture described in the README.

> One complication is that reactor-netty and reactor-core currently rely on slf4j for their internal logging. 

This is not entirely true, as `reactor-core` has its own `Logger` abstraction. The _default_ implementation that is picked up is either `slf4j` in case it is on the classpath OR logging to the console otherwise. Alternatively that fallback can be changed to JDK loggers via a system property.

The `Loggers` class let users switch to a different `Logger` factory: https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/util/Loggers.java#L135

So this project could potentially offer a 4th option, compatible with `Loggers.useCustomLoggers` above.

The main difficulty I guess is that all these logging libraries and facades expose blocking imperative methods (including the reactor-core one)...

> The logback-netty library would expose an interface similar to the current slf4j interface, but all the log-writing methods would return ChannelFuture objects instead of void.

Reactor-core's only dependency is Reactive Streams. It has some optional dependencies, like micrometer and slf4j, as `compileOnly` to detect and adapt to these libraries being in the classpath at runtime.

Even then, we try very hard to limit these `compileOnly` dependencies to the bare minimum. Adding a dependency to `netty` in `reactor-core` would be a no-go (especially given there is an entire project dedicated to adapting `netty` and `reactor-core`: `reactor-netty`).

> would return [`ChannelFuture`|`Mono<Context>`] objects instead of `void`

Does it _has_ to? A log can be considered like a fire-and-forget operation, right? (ie the method returning, in an async logger, wouldn't guarantee that the log has been written).

I'm not sure that anybody would really like to apply backpressure on a log statement.
Instead, in a reactive application log statements are triggered in conjunction with reactive streams signals, like `onNext`, `onComplete`, `cancel`, `onSubscribe`, etc... Some of these signals are themselves driven by backpressure.

This might make sense internally to the logging infrastructure, but I don't think exposing this to the user writing the log statement is that beneficial.

And this is all assuming that users are willing to write "reactive" log statements, explicitly as part of their chain of operators! A lot of users wishfully think that calling any 3rd-party library with an slf4j log statement in it from inside a reactor operator (like the lambda of a `map`) will magically fill the MDC...

NB: I've written a blog post about a possible approach to do explicit logging with reduced overhead a while back (some of it may now be a bit outdated / have better solutions): https://simonbasle.github.io/2018/02/contextual-logging-with-reactor-context-and-mdc/

**Comment by johncfranco** [comment]
Hello, thank you for the clarifications regarding reactor-core's internal logging.  I'll update the README with the information about the ability to tell reactor-core to use a specific logger factory even when slf4j is available.  Am I correct to think that, regardless of the factory in use, the reactor-core code uses the loggers produced by the factory in contexts where blocking I/O is dangerous?

The matter of whether logging is fire-and-forget is central to the premise of reliable application logging.  For organizations that are able to satisfy their operational needs while tolerating gaps in logging, fire-and-forget can be fine, but I've worked in an organization that treats gaps in application logs as system outages on a par with a network link going bad: automated alerts page operational personnel who are responsible for ensuring reliability, and any interruption requires an investigation, report, and measures to prevent recurrence.  All the code was imperative, and all the logging used blocking I/O, effectively including the logging in the imperative equivalent of backpressure.  If a log statement threw an exception, the exception would propagate just as (for example) a database communications error would.

I see this library as the reactive equivalent of that organization's imperative logging.

Your blog post seems to have been incorporated into the official `projectreactor.io` [FAQ](https://projectreactor.io/docs/core/release/reference/#faq.mdc). Reading that FAQ is what led me to consider making this library: confining application logging to the `doOn*` signal handlers seemed too restrictive, and I wanted log statements to be able to participate in backpressure just as any other I/O would.

**Comment by simonbasle** [comment]
makes sense @johncfranco thanks for the clarification about log interruptions being considered as outages in some organizations. I'm the main author of the reactor reference documentation, so it makes sense you found similar stuff in the FAQ 😉
